#!/usr/bin/env python
from cablestats.munin_helper import CableModemPlugin

class CMUpstreamPowerPlugin(CableModemPlugin):
	cm_title = 'Upstream Power'
	cm_direction = 'upstream'
	cm_field = 'channel_powerd_bm_v'
	vlable = "Power (dBmV)"
	category = "cable"

	def channel_info(self, ch):
		return "Channel ID: {}, Frequency: {} Hz, Modulation: {}".format(
			self.data[ch]['channel_id'],
			self.data[ch]['frequency'],
			self.data[ch]['modu'],
			)

if __name__ == "__main__":
	CMUpstreamPowerPlugin().run()