#!/usr/bin/env python
from cablestats.munin_helper import CableModemPlugin


class CMDownstreamSNRPlugin(CableModemPlugin):
    title = 'Downstream SNR'
    direction = 'downstream'
    field = 'snr'
    vlabel = 'SNR (dB)'
    category = 'Cable'
    critical = "30:" # Less than 30db is bad m'kay

    def channel_info(self, ch):
        return "Frequency: {} Hz, Modulation: {}".format(
            self.data[ch]['frequency'],
            self.data[ch]['qam'],
        )

if __name__ == "__main__":
    CMDownstreamSNRPlugin().run()
