#!/usr/bin/env python
from cablestats.munin_helper import CableModemPlugin

class CMDownstreamPowerPlugin(CableModemPlugin):
	cm_title = 'Downstream Power'
	cm_direction = 'downstream'
	cm_field = 'channel_powerd_bm_v'
	vlable = "Power (dBmV)"
	category = "cable"

	def channel_info(self, ch):
		return "Frequency: {} Hz, Modulation: {}".format(
			self.data[ch]['frequency'],
			self.data[ch]['qam'],
			)

if __name__ == "__main__":
	CMDownstreamPowerPlugin().run()